from __future__ import annotations

from io import BytesIO
from pathlib import Path
import re
from typing import Any, Iterable

from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.worksheet import Worksheet

from .models import InputRecord, ProductResult, StoreResult, now_iso
from .utils import ensure_directory, safe_filename

HEADER_FILL = PatternFill("solid", fgColor="1F4E78")
HEADER_FONT = Font(color="FFFFFF", bold=True)
TITLE_FONT = Font(size=16, bold=True, color="1F4E78")
SUBTITLE_FONT = Font(size=11, italic=True, color="666666")
IMPORTED_FONT = Font(color="008000")
STATIC_FONT = Font(color="666666")
CAUTION_FILL = PatternFill("solid", fgColor="FCE4D6")
TEAL_FILL = PatternFill("solid", fgColor="DDEBF7")
THIN_BLUE = Side(style="thin", color="9EADCC")
INVALID_XML_CHARS = re.compile(r"[\x00-\x08\x0B\x0C\x0E-\x1F]")


def _excel_safe(value: Any) -> Any:
    """Prevent malformed XML and spreadsheet-formula injection in imported text."""
    if not isinstance(value, str):
        return value
    cleaned = INVALID_XML_CHARS.sub("", value)
    if cleaned.lstrip().startswith(("=", "+", "-", "@")):
        return "'" + cleaned
    return cleaned


def _write_rows(ws: Worksheet, headers: list[str], rows: Iterable[dict[str, Any]]) -> None:
    ws.append(headers)
    for row in rows:
        ws.append([_excel_safe(row.get(header, "")) for header in headers])


def _format_table(ws: Worksheet, *, freeze: str = "A2") -> None:
    if ws.max_row < 1:
        return
    ws.freeze_panes = freeze
    ws.auto_filter.ref = ws.dimensions
    ws.sheet_view.showGridLines = False
    for cell in ws[1]:
        cell.fill = HEADER_FILL
        cell.font = HEADER_FONT
        cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
        cell.border = Border(bottom=THIN_BLUE)
    for row in ws.iter_rows(min_row=2):
        for cell in row:
            cell.alignment = Alignment(vertical="top", wrap_text=True)
            if isinstance(cell.value, str) and cell.value.startswith(("https://", "http://")):
                cell.hyperlink = cell.value
                cell.style = "Hyperlink"
            else:
                cell.font = IMPORTED_FONT
    for col_idx, column_cells in enumerate(ws.columns, start=1):
        values = [str(cell.value) if cell.value is not None else "" for cell in column_cells]
        max_len = min(max([len(value) for value in values] + [10]), 58)
        ws.column_dimensions[get_column_letter(col_idx)].width = max(12, max_len + 2)
    ws.row_dimensions[1].height = 34


def _format_number_columns(ws: Worksheet, currency_headers: set[str], number_headers: set[str]) -> None:
    header_map = {cell.value: cell.column for cell in ws[1] if cell.value}
    for header in currency_headers:
        col = header_map.get(header)
        if col:
            for row in range(2, ws.max_row + 1):
                ws.cell(row=row, column=col).number_format = '$#,##0.00;[Red]($#,##0.00);-'
    for header in number_headers:
        col = header_map.get(header)
        if col:
            for row in range(2, ws.max_row + 1):
                ws.cell(row=row, column=col).number_format = '#,##0.0'


def _add_summary_sheet(
    wb: Workbook,
    *,
    product_count: int,
    store_count: int,
    input_count: int,
    location: str,
    run_notes: str,
) -> Worksheet:
    ws = wb.active
    ws.title = "Summary"
    ws.sheet_view.showGridLines = False
    ws["A1"] = "Product Finder Run Summary"
    ws["A1"].font = TITLE_FONT
    ws["A2"] = (
        "Auto-generated by Product Hunter. Verify price, shipping, availability, and seller details before purchasing."
    )
    ws["A2"].font = SUBTITLE_FONT

    rows = [
        ("Generated at", now_iso()),
        ("Search location", location or "Not specified"),
        ("Inputs processed", input_count),
        ("Product listings found", product_count),
        ("Nearby/local store results found", store_count),
        ("Run notes", run_notes or ""),
    ]
    start = 4
    for offset, (label, value) in enumerate(rows):
        row = start + offset
        ws.cell(row=row, column=1, value=label)
        ws.cell(row=row, column=2, value=_excel_safe(value))
        ws.cell(row=row, column=1).font = Font(bold=True, color="666666")
        ws.cell(row=row, column=2).font = STATIC_FONT if label in {"Generated at", "Search location"} else IMPORTED_FONT
        ws.cell(row=row, column=1).fill = TEAL_FILL
        ws.cell(row=row, column=2).alignment = Alignment(wrap_text=True, vertical="top")

    ws["A12"] = "Important limitation"
    ws["A12"].font = Font(bold=True, color="9C6500")
    ws["A12"].fill = CAUTION_FILL
    ws["B12"] = (
        "Retailer pages change quickly. Nearby store results identify possible stores, not guaranteed live shelf stock "
        "unless the linked retailer explicitly shows availability."
    )
    ws["B12"].alignment = Alignment(wrap_text=True, vertical="top")
    ws["B12"].fill = CAUTION_FILL

    ws.column_dimensions["A"].width = 28
    ws.column_dimensions["B"].width = 95
    ws.row_dimensions[12].height = 48
    return ws


def _build_workbook(
    *,
    input_records: list[InputRecord],
    product_results: list[ProductResult],
    store_results: list[StoreResult],
    location: str,
    run_notes: str = "",
) -> Workbook:
    wb = Workbook()
    wb.properties.title = "Product Hunter Search Results"
    wb.properties.subject = "Retail product and nearby store search results"
    wb.properties.creator = "Product Hunter Web App"
    _add_summary_sheet(
        wb,
        product_count=len(product_results),
        store_count=len(store_results),
        input_count=len(input_records),
        location=location,
        run_notes=run_notes,
    )

    input_headers = [
        "input_type",
        "label",
        "extracted_product_name",
        "brand",
        "category",
        "confidence",
        "generated_queries",
        "notes",
        "source_url",
        "retrieved_at",
    ]
    ws_inputs = wb.create_sheet("Inputs")
    _write_rows(ws_inputs, input_headers, [record.to_row() for record in input_records])
    _format_table(ws_inputs)
    _format_number_columns(ws_inputs, set(), {"confidence"})

    product_headers = [
        "query",
        "input_source",
        "rank",
        "title",
        "seller",
        "price",
        "extracted_price",
        "delivery",
        "rating",
        "reviews",
        "condition",
        "snippet",
        "product_link",
        "seller_link",
        "thumbnail",
        "search_location",
        "retrieved_at",
        "raw_source",
    ]
    ws_products = wb.create_sheet("Product Results")
    _write_rows(ws_products, product_headers, [result.to_row() for result in product_results])
    _format_table(ws_products)
    _format_number_columns(ws_products, {"extracted_price"}, {"rating", "reviews"})

    store_headers = [
        "query",
        "rank",
        "title",
        "store_type",
        "address",
        "phone",
        "rating",
        "reviews",
        "hours",
        "website",
        "directions",
        "maps_link",
        "search_location",
        "retrieved_at",
        "raw_source",
    ]
    ws_stores = wb.create_sheet("Nearby Stores")
    _write_rows(ws_stores, store_headers, [result.to_row() for result in store_results])
    _format_table(ws_stores)
    _format_number_columns(ws_stores, set(), {"rating", "reviews"})

    return wb


def create_product_workbook_bytes(
    *,
    input_records: list[InputRecord],
    product_results: list[ProductResult],
    store_results: list[StoreResult],
    location: str,
    run_notes: str = "",
) -> tuple[str, bytes]:
    """Create a spreadsheet entirely in memory for safe multi-user hosting."""
    filename = safe_filename(f"product_search_results_{now_iso().replace(':', '-')}.xlsx")
    wb = _build_workbook(
        input_records=input_records,
        product_results=product_results,
        store_results=store_results,
        location=location,
        run_notes=run_notes,
    )
    buffer = BytesIO()
    wb.save(buffer)
    buffer.seek(0)
    return filename, buffer.getvalue()


def create_product_workbook(
    *,
    input_records: list[InputRecord],
    product_results: list[ProductResult],
    store_results: list[StoreResult],
    location: str,
    output_dir: str | Path = "exports",
    run_notes: str = "",
) -> Path:
    """Create the same workbook on disk for local or offline use."""
    output_path = ensure_directory(output_dir)
    filename, workbook_bytes = create_product_workbook_bytes(
        input_records=input_records,
        product_results=product_results,
        store_results=store_results,
        location=location,
        run_notes=run_notes,
    )
    workbook_path = output_path / filename
    workbook_path.write_bytes(workbook_bytes)
    return workbook_path
